.nix:
  # image: registry.gitlab.com/cynerd/gitlab-ci-nix@sha256:f36756b8634942d94b4f98c685b8133a782116a635c7b82743f48b3ed5d4192c
  image: registry.gitlab.com/cynerd/gitlab-ci-nix
  # Currently not supported by provided runner
  # tags: ["docker"]
  cache:
    when: "always"
    key: "nix-cache"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after

stages:
  - lint
  - build
  - deploy

checks:
  extends: .nix
  stage: lint
  script: nix flake check --all-systems

diff:
  extends: .nix
  stage: lint
  script: |
    if [ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]; then
      OLD="$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    else
      OLD="$CI_COMMIT_BEFORE_SHA"
    fi
    nix develop --command git latexdiff --run-biber --no-view --output diff.pdf $OLD HEAD
  artifacts:
    paths:
      - diff.pdf

build:document:
  extends: .nix
  stage: build
  script: |
    nix build .
    # Fix for https://gitlab.com/gitlab-org/gitlab/-/issues/19746
    BUILD_RESULT="$(realpath result)"
    unlink result
    cp --archive --no-target-directory "$BUILD_RESULT" public
  artifacts:
    paths:
      - "public/"

pages:
  stage: deploy
  script: ":"
  artifacts:
    paths:
      - "public/"
