.nix:
  image: registry.gitlab.com/cynerd/gitlab-ci-nix@sha256:f36756b8634942d94b4f98c685b8133a782116a635c7b82743f48b3ed5d4192c
  # Currently not supported by provided runner
  # tags: ["docker"]
  cache:
    when: "always"
    key: "nix-cache"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after
pages:
  extends: .nix
  script: |
    nix build .#document 
    # fix https://gitlab.com/gitlab-org/gitlab/-/issues/19746
    BUILD_RESULT="$(realpath result)"
    unlink result
    cp --archive --no-target-directory "$BUILD_RESULT" public
  artifacts:
    paths:
      - "public/"
