name: Document Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main      

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
      
    - name: Run nix flake build
      run: nix build .#document

    - name: Upload Document 
      uses: actions/upload-artifact@v4
      with:
        name: document
        path: result/document.pdf
        overwrite: true
